### ISSUE TITLE
/bin/sh gone with python Anaconda virtual environments?

### ISSUE THREAD

**Issue by brainstorm** [docker-slim/docker-slim#117]
Given [this Dockerfile](https://github.com/umccr/umccrise/blob/master/dockerfiles/Dockerfile), after running `docker-slim` (via [AWS CodeBuild BuildSpec CI/CD file](https://github.com/umccr/umccrise/blob/master/buildspec.yml)) it seems to let go of `/bin/sh`... can anybody explain why before I delve into the code and general docker-slim strategy? :)

Unsure but perhaps related (and good repro) for issue https://github.com/docker-slim/docker-slim/issues/14? I am using the following docker-slim command line:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim --in-container build --http-probe=false $ECR:umccrise-$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH --tag $ECR:umccrise-$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH.slim
```

Happy to share further logs and context for this if needed, cheers!

```
[Container] 2019/12/18 11:03:58 Running command docker run -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim --in-container build --http-probe=false $ECR:umccrise-$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH --tag $ECR:umccrise-$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH.slim 
Unable to find image 'dslim/docker-slim:latest' locally 
latest: Pulling from dslim/docker-slim 
282d05007e0d: Pulling fs layer 
282d05007e0d: Download complete 
282d05007e0d: Pull complete 
Digest: sha256:d3fd45591048cc59e9e1494835db461e0068fb777537ef014854f7423e192772 
Status: Downloaded newer image for dslim/docker-slim:latest 
time="2019-12-18T11:04:14.693489331Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/4dd2f2ab41a777868270d6927169e50a20e781604817aa81dd52659e45fc0575/shim.sock" debug=false pid=9525  
docker-slim[build]: info=probe message='changing continue-after from probe to enter because http-probe is disabled' 
docker-slim[build]: state=started 
docker-slim[build]: info=params target=843407916570.dkr.ecr.ap-southeast-2.amazonaws.com/umccr:umccrise-NOTAG-715441723b continue.mode=enter 
docker-slim[build]: state=image.inspection.start 
docker-slim[build]: info=image id=sha256:8004f3f670ac0713425d41884881066e0fe82b2a014f0b0105be26f73eb283aa size.bytes=11116957340 size.human=11 GB 
docker-slim[build]: info=image.stack index=0 name='ubuntu:16.04' id='sha256:56bab49eef2ef07505f6a1b0d5bd3a601dfc3c76ad4460f24c91d6fa298369ab' 
docker-slim[build]: info=image.stack index=1 name='843407916570.dkr.ecr.ap-southeast-2.amazonaws.com/umccr:umccrise-NOTAG-715441723b' id='sha256:8004f3f670ac0713425d41884881066e0fe82b2a014f0b0105be26f73eb283aa' 
docker-slim[build]: state=image.inspection.done 
docker-slim[build]: state=container.inspection.start 
time="2019-12-18T11:04:15.227149616Z" level=info msg="Layer sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef cleaned up" 
docker-slim[build]: info=container status=created name=dockerslimk_1_20191218110415 id=3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315 
time="2019-12-18T11:04:15.706991243Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315/shim.sock" debug=false pid=9648  
docker-slim[build]: info=cmd.startmonitor status=sent 
docker-slim[build]: info=event.startmonitor.done status=received 
docker-slim[build]: info=container name=dockerslimk_1_20191218110415 id=3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315 target.port.list=[] target.port.info=[] message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER' 
docker-slim[build]: info=continue.after mode=enter message='provide the expected input to allow the container inspector to continue its execution' 
docker-slim[build]: info=prompt message='USER INPUT REQUIRED, PRESS <ENTER> WHEN YOU ARE DONE USING THE CONTAINER' 
docker-slim[build]: state=container.inspection.finishing 
time="2019-12-18T11:04:26.240596977Z" level=info msg="shim reaped" id=3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315  
time="2019-12-18T11:04:26.250872768Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" 
time="2019-12-18T11:04:26.371559824Z" level=warning msg="3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/3dc9cb664879bae30040b556d873a1d064ab773f0532b853ba9217c952385315/mounts/shm, flags: 0x2: no such file or directory" 
docker-slim[build]: state=container.inspection.artifact.processing 
docker-slim[build]: state=container.inspection.done 
docker-slim[build]: state=building message='building minified image' 
time="2019-12-18T11:04:28.626526431Z" level=info msg="Layer sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef cleaned up" 
time="2019-12-18T11:04:29.774991031Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:29.994522372Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:30.159216667Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:30.326488749Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:30.486972939Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:30.679525373Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:30.850356790Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:31.026751110Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
time="2019-12-18T11:04:31.207166347Z" level=info msg="Layer sha256:34a39f193026946bf7c4c3cf7bbce187fac1ac1cb0074178660c31a2db4c2d70 cleaned up" 
docker-slim[build]: state=completed 
docker-slim[build]: info=results status='MINIFIED BY 195.52X [11116957340 (11 GB) => 56859375 (57 MB)]' 
docker-slim[build]: info=results  image.name=843407916570.dkr.ecr.ap-southeast-2.amazonaws.com/umccr:umccrise-NOTAG-715441723b.slim image.size='57 MB' data=true 
docker-slim[build]: info=results  artifacts.location='/bin/.docker-slim-state/images/8004f3f670ac0713425d41884881066e0fe82b2a014f0b0105be26f73eb283aa/artifacts' 
docker-slim[build]: info=results  artifacts.report=creport.json 
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat 
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile 
docker-slim[build]: info=results  artifacts.seccomp=843407916570.dkr.ecr.ap-southeast-2.amazonaws.com-umccr-seccomp.json 
docker-slim[build]: info=results  artifacts.apparmor=843407916570.dkr.ecr.ap-southeast-2.amazonaws.com-umccr-apparmor-profile 
docker-slim[build]: state=done 
docker-slim[build]: info=report file='slim.report.json' 
time="2019-12-18T11:04:31.860561642Z" level=info msg="shim reaped" id=4dd2f2ab41a777868270d6927169e50a20e781604817aa81dd52659e45fc0575  
time="2019-12-18T11:04:31.870663861Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" 
time="2019-12-18T11:04:32.015253963Z" level=warning msg="4dd2f2ab41a777868270d6927169e50a20e781604817aa81dd52659e45fc0575 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/4dd2f2ab41a777868270d6927169e50a20e781604817aa81dd52659e45fc0575/mounts/shm, flags: 0x2: no such file or directory" 
 
[Container] 2019/12/18 11:04:32 Running command docker run -t --cpus 4 -v=$PWD/umccrise_test_data/results/bcbio_test_project_docker:/output_dir -v=$PWD/umccrise_test_data/data/bcbio_test_project:/bcbio_project -v=/codebuild/output/refdata/genomes:/work/genomes $ECR:umccrise-$CODEBUILD_GIT_TAG-$SHORT_COMMIT_HASH.slim /bcbio_project -o /output_dir --genomes /work/genomes 
time="2019-12-18T11:04:32.208887900Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/e23f682c233a8f2cb5a9a5c3b32da605ad6be0c653b29e6266982fe20145f714/shim.sock" debug=false pid=9926  
Error processing line 1 of //miniconda/envs/umccrise/lib/python3.7/site-packages/matplotlib-3.1.1-py3.7-nspkg.pth: 
 
  Traceback (most recent call last): 
    File "//miniconda/envs/umccrise/lib/python3.7/site.py", line 168, in addpackage 
      exec(line) 
    File "<string>", line 1, in <module> 
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec 
  AttributeError: 'NoneType' object has no attribute 'loader' 
 
Remainder of file ignored 
umccrise_docker 
NOUSER 
 
/miniconda/envs/umccrise/bin/umccrise /bcbio_project -o /output_dir --genomes /work/genomes 
 
---------------------------------------------------------------------- 
Using genomes directory: /work/genomes 
snakemake  --snakefile /umccrise/umccrise/Snakefile --printshellcmds --directory /output_dir -j 1 --rerun-incomplete --restart-times 2  --config bcbio_project=/bcbio_project genomes_dir=/work/genomes upload_igv=no total_cores=1  
Traceback (most recent call last): 
  File "/miniconda/envs/umccrise/bin/umccrise", line 7, in <module> 
    exec(compile(f.read(), __file__, 'exec')) 
  File "/umccrise/scripts/umccrise", line 230, in <module> 
    main() 
  File "//miniconda/envs/umccrise/lib/python3.7/site-packages/click/core.py", line 764, in __call__ 
    return self.main(*args, **kwargs) 
  File "//miniconda/envs/umccrise/lib/python3.7/site-packages/click/core.py", line 717, in main 
    rv = self.invoke(ctx) 
  File "//miniconda/envs/umccrise/lib/python3.7/site-packages/click/core.py", line 956, in invoke 
    return ctx.invoke(self.callback, **ctx.params) 
  File "//miniconda/envs/umccrise/lib/python3.7/site-packages/click/core.py", line 555, in invoke 
    return callback(*args, **kwargs) 
  File "/umccrise/scripts/umccrise", line 193, in main 
    run_simple(cmd) 
  File "//miniconda/envs/umccrise/lib/python3.7/site-packages/ngs_utils/call_process.py", line 20, in run_simple 
    subprocess.check_call(cmd, shell=shell_arg, executable=executable_arg, env=env) 
  File "//miniconda/envs/umccrise/lib/python3.7/subprocess.py", line 342, in check_call 
    retcode = call(*popenargs, **kwargs) 
  File "//miniconda/envs/umccrise/lib/python3.7/subprocess.py", line 323, in call 
    with Popen(*popenargs, **kwargs) as p: 
  File "//miniconda/envs/umccrise/lib/python3.7/subprocess.py", line 775, in __init__ 
    restore_signals, start_new_session) 
  File "//miniconda/envs/umccrise/lib/python3.7/subprocess.py", line 1522, in _execute_child 
    raise child_exception_type(errno_num, err_msg, err_filename) 
FileNotFoundError: [Errno 2] No such file or directory: '/bin/sh': '/bin/sh' 
time="2019-12-18T11:04:32.735786323Z" level=info msg="shim reaped" id=e23f682c233a8f2cb5a9a5c3b32da605ad6be0c653b29e6266982fe20145f714  
time="2019-12-18T11:04:32.745838556Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" 
time="2019-12-18T11:04:32.895191383Z" level=warning msg="e23f682c233a8f2cb5a9a5c3b32da605ad6be0c653b29e6266982fe20145f714 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e23f682c233a8f2cb5a9a5c3b32da605ad6be0c653b29e6266982fe20145f714/mounts/shm, flags: 0x2: no such file or directory" 
```

**Comment by kcq** [comment]
Thanks for opening the issue @brainstorm ! Sorry for the headaches! Just to double check... is `umccrise` supposed to pick up the value of the `TEST_DATA_PATH` environment variable when it runs?

**Comment by brainstorm** [comment]
Hey @kcq, no worries at all and thanks a lot for having a look into it!

Which command are you running right now? [Does it look like the one in the docs](https://github.com/umccr/umccrise#docker)? Please let me know about the errors/issues you are facing, **umccrise** might not be trivial to run, unfortunately.

The test data should be picked up after cloning this repo: https://github.com/umccr/umccrise_test_data

I have been looking into how to share the reference genome data too (different from the test data), trimming it down from its current 538G:

```
spartan$ ls
cacao  GRCh37  hg38  pcgr  pyensembl
spartan$ du -hs .
538G	.
```

Although this shouldn't be strictly needed for a systems-level test run, IMHO. Tests should be able to run (quicker) on much smaller reference data.

/cc'ing the actual author, @vladsaveliev

**Comment by brainstorm** [comment]
@kcq, I bet I can close this issue in favour of https://github.com/docker-slim/docker-slim/issues/130 since it's easier to reproduce and does not involve pulling UMCCRISE's monolithic container and huge reference data files... 

Let me know if you need help or more feedback with issue #130.

**Comment by kcq** [comment]
@brainstorm #130 is related, but it's slightly different... Here we have an image with an application (umccrise) and there it's just a base image with the panda related libraries pre-installed. With this setup the main question is around the parameters the container needs when it's executed. Speaking of the command line parameters... which ones should i try with this tool?

**Comment by brainstorm** [comment]
The minimal command line parameters we use are those shown in buildspec.yml (used for the test suite):

https://github.com/umccr/umccrise/blob/master/buildspec.yml#L40

But the problem remains with the (big) bioinformatic reference files provisioning... you'll have to download and prepare a bunch of them yourself manually. Currently it's not clearly documented, let alone automated, fortunately it is in active discussion since we would like the general public to access and operate umccrise in the near future.

/cc @vladsaveliev @ohofmann @reisingerf
