### ISSUE TITLE
Too small image from centos and unusable

### ISSUE THREAD

**Issue by snnwolf** [docker-slim/docker-slim#131]
Build with docker-build:
```bash
docker-slim build t2/bo:centos
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=t2/bo:centos continue.mode=probe
docker-slim[build]: state=image.inspection.start
time="2020-02-19T14:01:28+03:00" level=fatal msg="docker-slim: failure" error="mkdir /usr/local/bin/.docker-slim-state: permission denied" stack="goroutine 1 [running]:\nruntime/debug.Stack(0x203000, 0x203000, 0x203000)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0xb6c9c0, 0xc0001793b0)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/pkg/util/fsutil.PrepareImageStateDirs(0x0, 0x0, 0xc0000f2410, 0x47, 0x1, 0x31, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/fsutil/fsutil.go:574 +0x400\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x9c4e01, 0xa92aae, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa80000, 0xc00001efc0, ...)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/commands/build.go:180 +0x958\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc00048c160, 0x0, 0xc0004902b0)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:775 +0x1709\ngithub.com/urfave/cli.HandleAction(0x9b03a0, 0xab7478, 0xc00048c160, 0xc00048c160, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.Command.Run(0xa8978f, 0x5, 0x0, 0x0, 0xc000448570, 0x1, 0x1, 0xaab688, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x51c\ngithub.com/urfave/cli.(*App).Run(0xc000456000, 0xc00008e150, 0x3,0x3, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x718\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:1159 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim@/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.26.1|2ec04e169b12a87c5286aa09ef44eac1cea2c7a1|2019-11-28_04:37:59PM"
```

**Comment by snnwolf** [comment]
sorry

**Comment by kcq** [comment]
@snnwolf This is an interesting error... This condition is handled properly on Mac OS, so `docker-slim` doesn't try to create its state directory where it lives if it's in `/usr/local/bin`. Need to do the same for Linux too. You can work around this using the `--state-path` parameters to tell `docker-slim` to store its state somewhere else.
