### ISSUE TITLE
Error "invalid context directory"

### ISSUE THREAD

**Issue by vc43** [docker-slim/docker-slim#154]
What means this error?

`docker-slim[build]: info=basic.image.name value=docker-slim-tmp-fat-image.15089.20200625042508
time="2020-06-25T07:25:08+03:00" level=fatal msg="docker-slim: failure" error="invalid context directory" stack="goroutine 1 [running]:\nruntime/debug.Stack(0xf506d8, 0xc000062f70, 0xc00047d160)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0xb9ab20, 0xc00001f6d0)\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0xc00005c0f0, 0xc000026cf0, 0x23, 0xc000163770, 0xc, 0x0, 0x0, 0x0, 0x0, 0xa11d01, ...)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/commands/build.go:139 +0x561b\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func10(0xc000098160, 0x0, 0xc0002bef00)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/cli.go:1655 +0x171a\ngithub.com/urfave/cli.HandleAction(0x9cd840, 0xad0bd8, 0xc000098160, 0xc000098160, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0x11a\ngithub.com/urfave/cli.Command.Run(0xaa0a83, 0x5, 0x0, 0x0, 0xc000130ff0, 0x1, 0x1, 0xac41f6, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x56e\ngithub.com/urfave/cli.(*App).Run(0xc000166000, 0xc0000b8180, 0x8, 0x8, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x7ae\ngithub.com/docker-slim/docker-slim/internal/app/master.(*InteractiveApp).execute(0xc000100ea0, 0xc00033e000, 0x5f)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/cli.go:328 +0x3c4\ngithub.com/c-bata/go-prompt.(*Prompt).Run(0xc0000b8680)\n\tgithub.com/c-bata/go-prompt@v0.2.3/prompt.go:85 +0x814\ngithub.com/docker-slim/docker-slim/internal/app/master.(*InteractiveApp).Run(...)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/cli.go:414\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func3(0xc000098dc0, 0x0, 0x0)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/cli.go:951 +0x70\ngithub.com/urfave/cli.HandleAction(0x9cd840, 0xad0bf8, 0xc000098dc0, 0xc000098dc0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0x11a\ngithub.com/urfave/cli.(*App).Run(0xc000166000, 0xc00001e1d0, 0x1, 0x1, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:285 +0x630\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim/internal/app/master/cli.go:2053 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.29.0|afff2c9679a697ebfc933360267253a10325269d|2020-03-18_07:11:20PM"
`

**Comment by kcq** [comment]
@vc43 looks like you are trying to build an optimized image from a Dockerfile and the build context you provided doesn't appear to be a valid directory. Your command line probably looked something like this: `docker-slim build --dockerfile YOUR_DOCKERFILE_NAME  YOUR_BUILD_CONTEXT_DIR`. Can you share your actual command line when you ran `docker-slim`? What does YOUR_BUILD_CONTEXT_DIR point to in your environment?
