### ISSUE TITLE
docker-slim build: support `--network=host`

### ISSUE THREAD

**Issue by openedhardware** [docker-slim/docker-slim#175]
I have a docker container to download a json object from the local server:

Here is a simple code:
```python
import requests

r = requests.get('http://0.0.0.0:1880/flows')
for f in r.json():
    if f['type'] == 'object-detection':
        print(f"Found a flow - {f}")
        model_name = f['model_name']
        url = "https://viso-public-storage.s3.eu-central-1.amazonaws.com/ObjDet/CPU/{}.tar.xz".format(model_name)
        print(f"Downloading - {url}")
        with open(f'/data/{model_name}.tar.gz', 'wb') as f:
            r = requests.get(url)
            f.write(r.content)
        break
print("Finished!")
```

Of course, `http://0.0.0.0:1880/flows` returns a json object, and I can parse it to download the the tar.xz file:

```shell
ubuntu@ubuntu-desktop:$ python3 main.py 
Found a flow - {'id': '813f8d7f.be7c1', 'type': 'object-detection', 'z': '47ed5c46.b85244', 'name': '', 'device_type': 'cpu', 'model_name': 'ssd_mobilenet_v1_coco_2018_01_28', 'labels': [], 'custom_model': False, 'model_url': '', 'tracking_algorithm': 'DLIB', 'tracking_quality': 5, 'tracking_cycle': 2, 'detection_threshold': 0.5, 'overlap_threshold': 0.7, 'x': 570, 'y': 460, 'wires': [['5c828fca.9dc5'], ['3ba8f140.c2503e']]}
Downloading - https://viso-public-storage.s3.eu-central-1.amazonaws.com/ObjDet/CPU/ssd_mobilenet_v1_coco_2018_01_28.tar.xz
Finished!
```

But `docker-slim build` command displays an error that it cannot access `0.0.0.0:1880`:
```
ubuntu@ubuntu-desktop:/test_docker_slim$ docker-slim build --http-probe=false  --mount /data:/data --include-path /usr/local/lib/python3.7/site-packages/certifi --show-clogs  ts
time="2021-01-26T08:11:33Z" level=info msg="sensor: args => []string{\"/opt/dockerslim/bin/docker-slim-sensor\"}"
time="2021-01-26T08:11:33Z" level=info msg="sensor: waiting for commands..."
time="2021-01-26T08:11:33Z" level=info msg="sensor: monitor starting..."
time="2021-01-26T08:11:33Z" level=info msg="fanmon: Run"
time="2021-01-26T08:11:33Z" level=info msg="ptmon: Run"
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcea6610e10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=1880): Max retries exceeded with url: /flows (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcea6610e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I even tried with `--network=host` option, but says another error:
```
ubuntu@ubuntu-desktop:/test_docker_slim$ docker-slim build --network=host  --http-probe=false  --mount /data:/data --include-path /usr/local/lib/python3.7/site-packages/certifi --show-clogs  ts
docker-slim: message='join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
docker-slim: message='join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
docker-slim[build]: info=probe message='changing continue-after from probe to enter because http-probe is disabled'
docker-slim[build]: state=started
docker-slim[build]: info=params target=ts continue.mode=enter rt.as.user=true keep.perms=true
docker-slim[build]: state=image.inspection.start
docker-slim[build]: info=image id=sha256:7ecfc64a27d82b46860bd56c8bb74bc3b559b9313f55336556d2a9fcbd80ec82 size.bytes=534676578 size.human=535 MB
docker-slim[build]: info=image.stack index=0 name='python:3.7-slim-buster' id='sha256:8109561612935afdd81f847b00ad1c37c13e0a3e0efce07f99687f710338bb28'
docker-slim[build]: info=image.stack index=1 name='ts:latest' id='sha256:7ecfc64a27d82b46860bd56c8bb74bc3b559b9313f55336556d2a9fcbd80ec82'
docker-slim[build]: state=image.inspection.done
docker-slim[build]: state=container.inspection.start
docker-slim[build]: info=container status=created name=dockerslimk_19880_20210126081302 id=393e525d95e2bb4636fb75698ca3708c36470f9bd0bc84193461e48acd5febab
time="2021-01-26T18:13:02+10:00" level=fatal msg="docker-slim: failure" error="docker-slim: error => missing comms ports" stack="goroutine 1 [running]:\nruntime/debug.Stack(0x0, 0xc00048a500, 0x16)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailWhen(0xc0003d8001, 0xdbaabc, 0x29)\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:34 +0x53\ngithub.com/docker-slim/docker-slim/internal/app/master/inspectors/container.(*Inspector).RunContainer(0xc00051a000, 0x4, 0xc0000f3960)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/inspectors/container/container_inspector.go:527 +0x1bf5\ngithub.com/docker-slim/docker-slim/internal/app/master/commands/build.OnCommand(0xc00039a1e0, 0x7ffd4ef6de3a, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/commands/build/handler.go:284 +0x172c\ngithub.com/docker-slim/docker-slim/internal/app/master/commands/build.glob..func1(0xc0003b2160, 0x0, 0xc0003b6460)\n\tgithub.com/docker-slim/docker-slim/internal/app/master/commands/build/cli.go:361 +0x1eb1\ngithub.com/urfave/cli.HandleAction(0xc55700, 0xdd9870, 0xc0003b2160, 0xc0003b2160, 0x0)\n\tgithub.com/urfave/cli@v1.22.4/app.go:526 +0x11a\ngithub.com/urfave/cli.Command.Run(0xd97655, 0x5, 0x0, 0x0, 0x155e550, 0x1, 0x1, 0xdcdc8a, 0x6c, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.4/command.go:174 +0x57a\ngithub.com/urfave/cli.(*App).Run(0xc000394000, 0xc0000300a0, 0xa, 0xa, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.4/app.go:279 +0x7c7\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/internal/app/master/app.go:15 +0x54\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.33.0|da7983050b8bf326c6f8e73ddce43a5b8d54da4b|2020-12-12_08:18:23PM"
```

How can I get the `0.0.0.0:1880/flows` working so that it can parse the model path and download the model file when building?

Steps to Reproduce the Problem
===============================

Hosted on this repo - https://github.com/openedhardware/test_docker_slim

Specifications
=================
  - Version: 1.3.3
  - Platform: Ubuntu

Cheers.

**Comment by kcq** [comment]
The app code should be `r = requests.get('http://127.0.0.1:1880/flows')`.

The latest set of enhancements addresses this condition. There'll be a new release soon.

**Comment by kcq** [comment]
try using the new release https://github.com/docker-slim/docker-slim/releases/tag/1.34.0

**Comment by openedhardware** [comment]
Yeah, it works!

**Comment by x-private-one** [comment]
cool

**Comment by kcq** [comment]
cool
