### ISSUE TITLE
"OCI runtime create failed" on Intel macOS

### ISSUE THREAD

**Issue by HarmlessSaucer** [docker-slim/docker-slim#284]
Expected Behavior
=================
When running docker-slim on any image on my macOS system, instead of evaluating the image, I get the following error below.

---
Actual Behavior
=================

```
docker-slim build website-docs
docker-slim: message='join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
docker-slim: message='join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
docker-slim: message='Github discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build info=param.http.probe message='using default probe'
cmd=build state=started
cmd=build info=params target='website-docs' continue.mode='probe' rt.as.user='true' keep.perms='true' tags='' target.type='image'
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:90ab091214d9ae8ebca376ad32bba5a6a548644eda95e45efe3ce5fe94cc0baa' size.bytes='102861136' size.human='103 MB'
cmd=build info=image.stack index='0' name='docker.apple.com/eccs-appeng/website-docs:latest' id='sha256:90ab091214d9ae8ebca376ad32bba5a6a548644eda95e45efe3ce5fe94cc0baa'
cmd=build info=image.exposed_ports list='80'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container status='created' name='dockerslimk_16754_20220201102647' id='3b5cba35317c6432324ffbe4f4c938c1363eb3a6b2462f2ec39e0febc60a5c38'
time="2022-02-01T10:26:48Z" level=fatal msg="docker-slim: failure" error="API error (400): OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"/opt/dockerslim/bin/docker-slim-sensor\": stat /opt/dockerslim/bin/docker-slim-sensor: no such file or directory: unknown" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn({0x19cd920, 0xc00000c060})\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:28 +0x5e\ngithub.com/docker-slim/docker-slim/pkg/app.(*ExecutionContext).FailOn(0xc0001a0fc0, {0x19cd920, 0xc00000c060})\n\tgithub.com/docker-slim/docker-slim/pkg/app/execontext.go:43 +0x49\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.OnCommand(_, _, {_, _}, _, {_, _}, {_, _}, {0x0, ...}, ...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/handler.go:893 +0x4e05\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.glob..func1(0xc0004b5760)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/cli.go:629 +0x4166\ngithub.com/urfave/cli.HandleAction({0x176ff00, 0x18cef98}, 0x5)\n\tgithub.com/urfave/cli@v1.22.4/app.go:526 +0xa8\ngithub.com/urfave/cli.Command.Run({{0x18878cf, 0x5}, {0x0, 0x0}, {0x1f96dd0, 0x1, 0x1}, {0x18c20a3, 0x6c}, {0x0, ...}, ...}, ...)\n\tgithub.com/urfave/cli@v1.22.4/command.go:174 +0x652\ngithub.com/urfave/cli.(*App).Run(0xc00039c000, {0xc000118090, 0x3, 0x3})\n\tgithub.com/urfave/cli@v1.22.4/app.go:279 +0x80c\ngithub.com/docker-slim/docker-slim/pkg/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/app.go:15 +0x38\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x17\n" version="darwin|Transformer|1.37.3|latest|latest"
```

---
Steps to Reproduce the Problem
===============================
 

  1. Installed docker-slim using Brew:  `brew install docker-slim` 
  2. Pull docker image from Artifactory (Image builds website in Alpine layer, then serves via httpd)
  3. Run test: `docker-slim build website-docs`

---
Troubleshooting
=================

- I removed docker-slim through Brew and manually installed by downloading the package manually and installing using:
```
unzip ds.zip
mv  dist_mac/docker-slim /usr/local/bin/
mv  dist_mac/docker-slim-sensor /usr/local/bin/
```
The issue persists.

- I created a Ubuntu 22.04 VM in VirtualBox and installed and Docker-Slim there.  This process works without issue there.

---
Specifications
=================
  - Version:  docker-slim version darwin|Transformer|1.37.3|latest|latest
  - Platform:  macOS Monterey 12.1 (21C52) - Intel

**Comment by kcq** [comment]
thanks for the report @HarmlessSaucer ! investigating...
