### ISSUE TITLE
Docker slim produces a broken nestjs / nodejs image 

### ISSUE THREAD

**Issue by jotaoncode** [docker-slim/docker-slim#285]
Expected Behavior
=================

The image to work as in previous builts

---
Actual Behavior
=================

Minimizes the size of the image properly but when I try to run it, it fails with an error.

---
Steps to Reproduce the Problem
===============================

I am trying to improve my docker images by minimizing as much as possible their size. In order to do so I did the follow steps with a nestjs example as a use case:

```
nest new testing-docker-slim
```
and then inside of it I created the following docker file, with multistage and also some differences on npm installation of packages in between production and development:

```
FROM node:17-alpine as base 
 
FROM base as development 
WORKDIR /app 
COPY . . 
RUN npm i 
CMD ["sh", "-c", "npm run start:dev"] 
 
FROM base as staging 
WORKDIR /app 
COPY . . 
RUN npm i 
RUN npm run build 
CMD ["sh", "-c", "npm run start:prod"] 
 
FROM base as production 
WORKDIR /app 
COPY --from=staging /app/dist ./dist 
COPY --from=staging /app/package.json /app/package-lock.json ./ 
RUN npm i --production 
CMD ["sh", "-c", "npm run start:prod"]
```
Added a docker ignore file with the following entries:

```
node_modules
.git
.idea
```
Created a docker images with the following command:
```
docker build . --target production -t testing-docker-slim 
```
And also with this command another images:
```
docker build . --target development -t testing-docker-slim-dev
```
The images have this size:
```
testing-docker-slim-dev    latest       4408308966c3   22 minutes ago      471MB
testing-docker-slim    latest       c688ff1bedc2   22 minutes ago      185MB
```
So we already have a reasonable improvement on size of image from 471Mb to 185Mb... Still I did a bit more of research and found out about 2 tools, [dive][1] and [docker slim][2].

dive in both images says that it is a 99% image efficiency score... so did not found out much with it that I could do with the image to improve.

then I saw docker slim which claims to have an extraordinary level of compression of images, and I run the following command:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build testing-docker-slim --expose 3000 --http-probe=false --continue-after=1
```
creating a beautiful image of this size:
```
testing-docker-slim.slim    latest       99a51a88a0f2   9 minutes ago       89.9MB
```
this size of image is a reasonable one but when I run the image to see if it is working as expected, it crashes with this error:

```
> testing-docker-slim@0.0.1 start:prod
> node dist/main

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'iterare'
Require stack:
- /app/node_modules/@nestjs/common/pipes/validation.pipe.js
- /app/node_modules/@nestjs/common/pipes/parse-array.pipe.js
- /app/node_modules/@nestjs/common/pipes/index.js
- /app/node_modules/@nestjs/common/index.js
- /app/node_modules/@nestjs/core/discovery/discovery-module.js
- /app/node_modules/@nestjs/core/discovery/index.js
- /app/node_modules/@nestjs/core/index.js
- /app/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@nestjs/common/pipes/validation.pipe.js',
    '/app/node_modules/@nestjs/common/pipes/parse-array.pipe.js',
    '/app/node_modules/@nestjs/common/pipes/index.js',
    '/app/node_modules/@nestjs/common/index.js',
    '/app/node_modules/@nestjs/core/discovery/discovery-module.js',
    '/app/node_modules/@nestjs/core/discovery/index.js',
    '/app/node_modules/@nestjs/core/index.js',
    '/app/dist/main.js'
  ]
}

Node.js v17.4.0
```
the same happens when I use docker slim on the multistage for development, but the docker multistage without using docker slim works perfectly fine.

It seems that docker slim is touching this modules or something as a like, the multistage versions without docker slim works just fine.
Should I try to change my Dockerfile in any specific way, or run the docker slim in a different way in order to get this running.

With the above steps it should be possible to reproduce and debug, but I am not a person of experience when it comes to Go, and not only it might take me sometime to get to the project to give a hand with a PR but also may be I am just miss using the tool, so please any help or guidance will be welcome.

**Comment by jotaoncode** [comment]
I was able to made it run by using a flag called `--include-path` and adding my own application folder to it

**Comment by kcq** [comment]
> I was able to made it run by using a flag called `--include-path` and adding my own application folder to it

What was the `--include-path` you used for it?

**Comment by kcq** [comment]
@jotaoncode thanks a lot for your very detailed ticket! Do you mind sharing more about the app? The Dockerfile you shared doesn't have any ports exposed in it. Curious how you run the app... 

Wonder if specifying custom http probes can eliminate the needs for the `--include-path` param.

**Comment by jotaoncode** [comment]
@kcq I am sorry for the delay on this answer, I will try the exposure of the http probes and may be that removes the need for `--include-path`, in my case the bundle was less than 100Mb when I tried the docker slim but it did not contain the /app folder at all. 
Later I followed some of the advices Jay in [this stackoverlow](https://stackoverflow.com/questions/70991824/how-to-minimize-properly-a-nestjs-nodejs-application-with-docker-slim-or-other/70993945#70993945) which also helped to reduce the size of the image by a 5 to 10% using tj prunes package.
The way I am running this is by using a minikube + skaffold and a k8s service that exposes the correspoding port 3000.

Also in the run of the docker slim I was doing:
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build testing-docker-slim --expose 3000 --http-probe=false --continue-after=1
```
meaning I was avoiding the http probe due to the fact that it fail to probe, but now that you mention I would like to try to use the docker expose and test the http probe too.

how does skaffold + minikube run this thing I guess down the line it might be doing something like `docker run image -p 80:80` meaning the service might only be using the -p parameter of docker... but not a 100% sure about it.

In the next 24 hours will drop a message saying if the exposure helped with the probe + removed the need of local path

**Comment by jotaoncode** [comment]
@kcq so some results and steps to reproduce the issue, I will reopen it because it is actually touching the image the adding or removing of this flag.

Steps to reproduce it (you may need nodejs installed, I have v16.13.1):

- using the nest - cli call the following `nest new testing-docker-slim` this will create a brand new nest project for you.
- copy in the folder testing-docker-slim the following docker ignore
```
node_modules
.git
.idea
```
changing .idea for anything your editor may be
- copy in the folder testing-docker-slim the following docker file
```
FROM node:17-alpine AS base
EXPOSE 3000

FROM base AS pruned
WORKDIR /app
COPY package.json package-lock.json ./
RUN apk update && apk add curl
RUN npm i --production
RUN curl -sf https://gobinaries.com/tj/node-prune | sh
RUN node-prune
EXPOSE 3000

FROM base as development
WORKDIR /app
COPY ./src ./src
COPY package.json package-lock.json tsconfig.build.json tsconfig.json .eslintrc.js .prettierrc ./
RUN npm i
RUN npm run build
EXPOSE 3000
CMD ["sh", "-c", "npm run start:dev"]

FROM base AS production
WORKDIR /app
COPY --from=development /app/dist ./dist
COPY --from=pruned /app/package.json /app/package-lock.json ./
COPY --from=pruned /app/node_modules ./node_modules
EXPOSE 3000
CMD ["sh", "-c", "npm run start:prod"]
```

- inside of the folder testing-docker-slim run the following command:
```
docker build . -t testing-docker-slim-production --target=production
```
this is the base image needed to slim.
- we can run the docker slim with included path:
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build testing-docker-slim-production --expose 3000 --continue-after=1 --include-path=/app --tag=yes.include.pat
```
- lets run it without the included path
```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build testing-docker-slim-production --expose 3000 --continue-after=1 --tag=no.include.path
```
- now the results of the images are:
```
yes.include.path                              latest                   fcefaece0bdd   4 seconds ago        97.6MB
no.include.path                               latest                   115d5fc27f97   About a minute ago   90.5MB
testing-docker-slim-production       latest                   63ab17071260   18 minutes ago       178MB
testing-docker-slim-development   latest                   2beb278dfdec   About an hour ago    396MB
node                                              17-alpine              c6a2764d974b   4 days ago           170MB
```
So we can see that the image created without the included path is smaller by 7.1Mb, similarly to the difference between testing-docker-slim production and node alpine base image. And the difference is as I see from dive the application itself is not included in one of the cases.

Here is the dive look on it for yes.include.path:

```
┃ ● Layers ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ │ Current Layer Contents ├─────────────────────────────────────────────────────────────────────────────────────────────────────
Cmp   Size  Command                                                                                                             Permission     UID:GID       Size  Filetree
     98 MB  FROM 9fbc224f963802b                                                                                                drwxr-xr-x         0:0     7.6 MB  ├── app
                                                                                                                                drwxr-xr-x         0:0      90 kB  │   ├── dist
│ Layer Details ├────────────────────────────────────────────────────────────────────────────────────────────────────────────── -rw-r--r--         0:0      181 B  │   │   ├── app.controller.d.ts
                                                                                                                                -rw-r--r--         0:0     1.6 kB  │   │   ├── app.controller.js
Tags:   (unavailable)                                                                                                           -rw-r--r--         0:0      426 B  │   │   ├── app.controller.js.map
Id:     9fbc224f963802bfdcfd3c69be1ecb12cb66561b78079e6ecef07463b5d143dc                                                        -rw-r--r--         0:0       35 B  │   │   ├── app.module.d.ts
Digest: sha256:1d93ffcd3e454c7bc028b91a7ee6e343af372dad43e2c8b6207eb8007fd8c6f3                                                 -rw-r--r--         0:0     1.1 kB  │   │   ├── app.module.js
Command:                                                                                                                        -rw-r--r--         0:0      351 B  │   │   ├── app.module.js.map
#(nop) ADD file:34af8a9357caa9ecae2eed8d57d9176416f27c6f07aeabbe253c9742004fb502 in /                                           -rw-r--r--         0:0       60 B  │   │   ├── app.service.d.ts
                                                                                                                                -rw-r--r--         0:0      960 B  │   │   ├── app.service.js
│ Image Details ├────────────────────────────────────────────────────────────────────────────────────────────────────────────── -rw-r--r--         0:0      277 B  │   │   ├── app.service.js.map
                                                                                                                                -rw-r--r--         0:0       11 B  │   │   ├── main.d.ts
Image name: yes.include.path                                                                                                    -rw-r--r--         0:0      340 B  │   │   ├── main.js
Total Image size: 98 MB                                                                                                         -rw-r--r--         0:0      287 B  │   │   ├── main.js.map
Potential wasted space: 0 B                                                                                                     -rw-r--r--         0:0      85 kB  │   │   └── tsconfig.build.tsbuildinfo
Image efficiency score: 100 %                                                                                                   drwxr-xr-x         0:0     6.9 MB  │   ├── node_modules
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── .bin
Count   Total Space  Path                                                                                                       -rwxrwxrwx         0:0        0 B  │   │   │   ├── mime → ../mime/cli.js
                                                                                                                                -rwxrwxrwx         0:0        0 B  │   │   │   ├── mkdirp → ../mkdirp/bin/cmd.js
                                                                                                                                -rwxrwxrwx         0:0        0 B  │   │   │   ├── opencollective → ../@nuxtjs/opencollective/bin/opencollective.js
                                                                                                                                -rwxrwxrwx         0:0        0 B  │   │   │   ├── rimraf → ../rimraf/bin.js
                                                                                                                                -rwxrwxrwx         0:0        0 B  │   │   │   └── uuid → ../uuid/dist/bin/uuid
                                                                                                                                -rw-r--r--         0:0      40 kB  │   │   ├── .package-lock.json
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @ampproject
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @angular-devkit
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @babel
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @bcoe
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @cspotcode
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @eslint
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @humanwhocodes
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @istanbuljs
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @jest
                                                                                                                                drwxr-xr-x         0:0        0 B  │   │   ├── @jridgewell
                                                                                                                                drwxr-xr-x         0:0     491 kB  │   │   ├── @nestjs
                                                                                                                                drwxr-xr-x         0:0     183 kB  │   │   │   ├── common
                                                                                                                                drwxr-xr-x         0:0     9.7 kB  │   │   │   │   ├── cache
                                                                                                                                -rw-r--r--         0:0      404 B  │   │   │   │   │   ├── cache.constants.js
                                                                                                                                -rw-r--r--         0:0     2.8 kB  │   │   │   │   │   ├── cache.module.js
                                                                                                                                -rw-r--r--         0:0     1.1 kB  │   │   │   │   │   ├── cache.providers.js
                                                                                                                                drwxr-xr-x         0:0     1.3 kB  │   │   │   │   │   ├── decorators
                                                                                                                                -rw-r--r--         0:0      663 B  │   │   │   │   │   │   ├── cache-key.decorator.js
                                                                                                                                -rw-r--r--         0:0      340 B  │   │   │   │   │   │   ├── cache-ttl.decorator.js
                                                                                                                                -rw-r--r--         0:0      251 B  │   │   │   │   │   │   └── index.js
                                                                                                                                -rw-r--r--         0:0      197 B  │   │   │   │   │   ├── default-options.js
                                                                                                                                -rw-r--r--         0:0      425 B  │   │   │   │   │   ├── index.js
                                                                                                                                drwxr-xr-x         0:0     3.2 kB  │   │   │   │   │   ├── interceptors

```

and the one of no include flag is:
```
┃ ● Layers ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ │ Current Layer Contents ├─────────────────────────────────────────────────────────────────────────────────────────────────────
Cmp   Size  Command                                                                                                             Permission     UID:GID       Size  Filetree
     90 MB  FROM 19b040da3ef8df9                                                                                                drwxr-xr-x         0:0     466 kB  ├── app
                                                                                                                                drwxr-xr-x         0:0      340 B  │   ├── dist
│ Layer Details ├────────────────────────────────────────────────────────────────────────────────────────────────────────────── -rw-r--r--         0:0      340 B  │   │   └── main.js
                                                                                                                                drwxr-xr-x         0:0     464 kB  │   ├── node_modules
Tags:   (unavailable)                                                                                                           drwxr-xr-x         0:0      92 kB  │   │   ├── @nestjs
Id:     19b040da3ef8df9e1ab5b58c81fd92c602ba781a889aa27a8ead56d5b11da399                                                        drwxr-xr-x         0:0      82 kB  │   │   │   ├── common
Digest: sha256:fcc4b43554448f09a70652626a92fc5b0bb2d881ad480fc64fc480bb235a4a51                                                 drwxr-xr-x         0:0     9.3 kB  │   │   │   │   ├── cache
Command:                                                                                                                        -rw-r--r--         0:0      404 B  │   │   │   │   │   ├── cache.constants.js
#(nop) ADD file:a0b31213d52b5ad223e21554ab3a3ab7532a3725d13c0bdb926704fd69df2fc1 in /                                           -rw-r--r--         0:0     2.8 kB  │   │   │   │   │   ├── cache.module.js
                                                                                                                                -rw-r--r--         0:0     1.1 kB  │   │   │   │   │   ├── cache.providers.js
│ Image Details ├────────────────────────────────────────────────────────────────────────────────────────────────────────────── drwxr-xr-x         0:0     1.3 kB  │   │   │   │   │   ├── decorators
                                                                                                                                -rw-r--r--         0:0      663 B  │   │   │   │   │   │   ├── cache-key.decorator.js
Image name: no.include.path                                                                                                     -rw-r--r--         0:0      340 B  │   │   │   │   │   │   ├── cache-ttl.decorator.js
Total Image size: 90 MB                                                                                                         -rw-r--r--         0:0      251 B  │   │   │   │   │   │   └── index.js
Potential wasted space: 0 B                                                                                                     -rw-r--r--         0:0      197 B  │   │   │   │   │   ├── default-options.js
Image efficiency score: 100 %                                                                                                   -rw-r--r--         0:0      425 B  │   │   │   │   │   ├── index.js
                                                                                                                                drwxr-xr-x         0:0     3.2 kB  │   │   │   │   │   └── interceptors
Count   Total Space  Path                                                                                                       -rw-r--r--         0:0     3.0 kB  │   │   │   │   │       ├── cache.interceptor.js
                                                                                                                                -rw-r--r--         0:0      179 B  │   │   │   │   │       └── index.js
                                                                                                                                -rw-r--r--         0:0     2.5 kB  │   │   │   │   ├── constants.js
                                                                                                                                drwxr-xr-x         0:0      43 kB  │   │   │   │   ├── decorators
                                                                                                                                drwxr-xr-x         0:0      22 kB  │   │   │   │   │   ├── core
                                                                                                                                -rw-r--r--         0:0      814 B  │   │   │   │   │   │   ├── apply-decorators.js
                                                                                                                                -rw-r--r--         0:0      580 B  │   │   │   │   │   │   ├── bind.decorator.js
                                                                                                                                -rw-r--r--         0:0      988 B  │   │   │   │   │   │   ├── catch.decorator.js
                                                                                                                                -rw-r--r--         0:0     3.2 kB  │   │   │   │   │   │   ├── controller.decorator.js
                                                                                                                                -rw-r--r--         0:0      670 B  │   │   │   │   │   │   ├── dependencies.decorator.js
                                                                                                                                -rw-r--r--         0:0     2.1 kB  │   │   │   │   │   │   ├── exception-filters.decorator.js
                                                                                                                                -rw-r--r--         0:0     1.1 kB  │   │   │   │   │   │   ├── index.js
                                                                                                                                -rw-r--r--         0:0     2.3 kB  │   │   │   │   │   │   ├── inject.decorator.js
                                                                                                                                -rw-r--r--         0:0     2.0 kB  │   │   │   │   │   │   ├── injectable.decorator.js
                                                                                                                                -rw-r--r--         0:0     1.2 kB  │   │   │   │   │   │   ├── optional.decorator.js
                                                                                                                                -rw-r--r--         0:0     1.0 kB  │   │   │   │   │   │   ├── set-metadata.decorator.js
                                                                                                                                -rw-r--r--         0:0     1.9 kB  │   │   │   │   │   │   ├── use-guards.decorator.js
                                                                                                                                -rw-r--r--         0:0     2.1 kB  │   │   │   │   │   │   ├── use-interceptors.decorator.js
                                                                                                                                -rw-r--r--         0:0     1.7 kB  │   │   │   │   │   │   ├── use-pipes.decorator.js
                                                                                                                                -rw-r--r--         0:0      580 B  │   │   │   │   │   │   └── version.decorator.js
                                                                                                                                drwxr-xr-x         0:0      18 kB  │   │   │   │   │   ├── http
                                                                                                                                -rw-r--r--         0:0     1.5 kB  │   │   │   │   │   │   ├── create-route-param-metadata.decorator.js
                                                                                                                                -rw-r--r--         0:0      789 B  │   │   │   │   │   │   ├── header.decorator.js
                                                                                                                                -rw-r--r--         0:0      703 B  │   │   │   │   │   │   ├── http-code.decorator.js
                                                                                                                                -rw-r--r--         0:0      685 B  │   │   │   │   │   │   ├── index.js
                                                                                                                                -rw-r--r--         0:0      471 B  │   │   │   │   │   │   ├── redirect.decorator.js
                                                                                                                                -rw-r--r--         0:0      659 B  │   │   │   │   │   │   ├── render.decorator.js
                                                                                                                                -rw-r--r--         0:0     3.4 kB  │   │   │   │   │   │   ├── request-mapping.decorator.js
                                                                                                                                -rw-r--r--         0:0     9.1 kB  │   │   │   │   │   │   ├── route-params.decorator.js

```

Running yest.include.path does the following output:

```
➜  testing-docker-slim git:(master) ✗ docker run yes.include.path

> testing-docker-slim@0.0.1 start:prod
> node dist/main

[Nest] 18  - 02/15/2022, 8:46:33 AM     LOG [NestFactory] Starting Nest application...
[Nest] 18  - 02/15/2022, 8:46:33 AM     LOG [InstanceLoader] AppModule dependencies initialized +33ms
[Nest] 18  - 02/15/2022, 8:46:33 AM     LOG [RoutesResolver] AppController {/}: +4ms
[Nest] 18  - 02/15/2022, 8:46:33 AM     LOG [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 18  - 02/15/2022, 8:46:33 AM     LOG [NestApplication] Nest application successfully started +2ms

```
while no include path does the following output:
```

> testing-docker-slim@0.0.1 start:prod
> node dist/main

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './internal/operators/retryWhen'
Require stack:
- /app/node_modules/rxjs/dist/cjs/index.js
- /app/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js
- /app/node_modules/@nestjs/common/cache/interceptors/index.js
- /app/node_modules/@nestjs/common/cache/index.js
- /app/node_modules/@nestjs/common/index.js
- /app/node_modules/@nestjs/core/discovery/discovery-module.js
- /app/node_modules/@nestjs/core/discovery/index.js
- /app/node_modules/@nestjs/core/index.js
- /app/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/rxjs/dist/cjs/index.js:276:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/rxjs/dist/cjs/index.js',
    '/app/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js',
    '/app/node_modules/@nestjs/common/cache/interceptors/index.js',
    '/app/node_modules/@nestjs/common/cache/index.js',
    '/app/node_modules/@nestjs/common/index.js',
    '/app/node_modules/@nestjs/core/discovery/discovery-module.js',
    '/app/node_modules/@nestjs/core/discovery/index.js',
    '/app/node_modules/@nestjs/core/index.js',
    '/app/dist/main.js'
  ]
}

Node.js v17.5.0

```

So I will reopen this as a bug because not adding this flag --include-path=/app is actually losing the needed information for the application, although for the moment as a workaround I can just include the flag and that still disminushes the size in a cool way. May be I am missing something in the way I am running docker slim and any guidance will be welcome.

Thanks for your help with this nice lib, it is so much better to have reasonable size images

**Comment by kcq** [comment]
@jotaoncode Thanks a lot for the repro steps! Super helpful! I'll use this as the foundation for a new sample app too. We'll have it by default. In the meantime you might benefit from the new `--include-node-package` where you should be able to specify the name of your app's package as the flag value and it should do something similar to the `--include-path=/app` flag you have, but without using an absolute path.

**Comment by kcq** [comment]
@jotaoncode there's a new nest.js example and it has a number of helper scripts to repro your condition and to minify the image properly: https://github.com/docker-slim/examples/tree/master/node_nest_app

Short version: 

You ended up with those failures because you used the wait/time out continue after mode and the wait time you specified was too short (`--continue-after=1`). This script repros what you had: `_slim_multi_repro_fail.sh`

If you set the wait to 15 seconds then it should be ok and you won't need the `--include-path` param: `_slim_multi_repro_ok.sh`

The nest example has a number of other helper scripts that show how the app can be minified (3 versions):

Version 1 (using your multi-stage Dockerfile / `Dockerfile.multi`):

This version relies on the standard http probing behavior (no `continue-after` flag).

To build the fat image run: `./_build_multi.sh`

To minify run: `./_slim_multi_docker.sh`

To run the minified app: `./_run_multi_slim_docker.sh`

Version 2 (default production version / `Dockerfile`): 

To build the fat image run: `./_build.sh`

To minify run: `./_slim.sh`

To run the minified app: `./_run_slim.sh`

Version 3 (default dev version / `Dockerfile.dev`): 

To build the fat image run: `./_build_dev.sh`

To minify run: `./_slim_dev.sh`

To run the minified app: `./_run_dev_slim.sh`

Note that the helper scripts for version 2 and 3 rely on the locally installed `docker-slim` (not using the container version)

**Comment by jotaoncode** [comment]
@kcq  wow thanks for the example folder to follow up on this case, I will take a look into it today. Was a bit disconnected for the last 6 weeks.
