### ISSUE TITLE
DockerSlim is not working

### ISSUE THREAD

**Issue by dshamanthreddy** [docker-slim/docker-slim#410]
Expected Behavior
=================

After issuing the `docker-slim build --target` it has build a slim image

---
Actual Behavior
=================

It not building the image but giving below error

`docker-slim build --target dslimexamples/java-dropwizard-standard:latest --tag dslimexamples/java-dropwizard-standard:slim
app='docker-slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='docker-slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='docker-slim' message='GitHub Discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build info=param.http.probe message='using default probe'
cmd=build state=started
cmd=build info=params rt.as.user='true' keep.perms='true' tags='dslimexamples/java-dropwizard-standard:slim' target.type='image' target='dslimexamples/java-dropwizard-standard:latest' continue.mode='probe'
cmd=build state=image.inspection.start
cmd=build info=image architecture='arm64' id='sha256:29cd07d1baacf9732b2c8dca29daa91e385d2a421d8bac10079a5bf601bd7f7e' size.bytes='534208747' size.human='534 MB'
cmd=build info=image.stack id='sha256:29cd07d1baacf9732b2c8dca29daa91e385d2a421d8bac10079a5bf601bd7f7e' index='0' name='dslimexamples/java-dropwizard-standard:latest'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container id='319ff4dcf58219b5333e6c0e39286fc3847c18af236dd8cc1f7a41043f9c3242' status='created' name='dockerslimk_6481_20221003025740'
cmd=build info=report file='slim.report.json'
time="2022-10-02T22:57:41-04:00" level=fatal msg="docker-slim: failure" error="API error (400): failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: \"/opt/dockerslim/bin/docker-slim-sensor\": stat /opt/dockerslim/bin/docker-slim-sensor: no such file or directory: unknown" stack="goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x64\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn({0x104f40a00, 0x140005f0fc0})\n\tgithub.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:28 +0x38\ngithub.com/docker-slim/docker-slim/pkg/app.(*ExecutionContext).FailOn(0x14000478840?, {0x104f40a00?, 0x140005f0fc0?})\n\tgithub.com/docker-slim/docker-slim/pkg/app/execontext.go:56 +0x44\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.OnCommand(_, _, {_, _}, _, _, _, _, _, _, ...)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/handler.go:1063 +0x4e34\ngithub.com/docker-slim/docker-slim/pkg/app/master/commands/build.glob..func1(0x1400045bdc0)\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/commands/build/cli.go:694 +0x3c88\ngithub.com/urfave/cli/v2.(*Command).Run(0x1054ffba0, 0x14000189b80)\n\tgithub.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4fc\ngithub.com/urfave/cli/v2.(*App).RunContext(0x14000083860, {0x104f484d0?, 0x1400012e008}, {0x1400012a120, 0x6, 0x6})\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:313 +0x860\ngithub.com/urfave/cli/v2.(*App).Run(...)\n\tgithub.com/urfave/cli/v2@v2.3.0/app.go:224\ngithub.com/docker-slim/docker-slim/pkg/app/master.Run()\n\tgithub.com/docker-slim/docker-slim/pkg/app/master/app.go:15 +0x4c\nmain.main()\n\tgithub.com/docker-slim/docker-slim/cmd/docker-slim/main.go:15 +0x1c4\n" version="darwin|Transformer|1.38.0|latest|latest"`

---
Steps to Reproduce the Problem
===============================

1. Build a docker image locally (java) 
2. docker-slim build --target dslimexamples/java-dropwizard-standard:latest --tag dslimexamples/java-dropwizard-standard:slim
3. error

---
Specifications
=================
  - Version: 1.38
  - Platform:Apple mac
<img width="760" alt="Screen Shot 2022-10-02 at 11 20 45 PM" src="https://user-images.githubusercontent.com/18470551/193496527-4d8e0478-dc31-48ff-acdf-616c665cf126.png">

**Comment by iximiuz** [comment]
I tried the fresh version (1.38) and it worked just fine.

```
docker-slim build --target dslimexamples/java-dropwizard-standard:latest --tag dslimexamples/java-dropwizard-standard:slim
app='docker-slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='docker-slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='docker-slim' message='GitHub Discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build info=param.http.probe message='using default probe'
cmd=build state=started
cmd=build info=params target.type='image' target='dslimexamples/java-dropwizard-standard:latest' continue.mode='probe' rt.as.user='true' keep.perms='true' tags='dslimexamples/java-dropwizard-standard:slim'
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:d24ca46f9b60b83f49dcb2182d3d6b6f3b2063c1508cb5a315cd2ef8a68a6160' size.bytes='534208747' size.human='534 MB' architecture='arm64'
cmd=build info=image.stack index='0' name='dslimexamples/java-dropwizard-standard:latest' id='sha256:d24ca46f9b60b83f49dcb2182d3d6b6f3b2063c1508cb5a315cd2ef8a68a6160'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container status='created' name='dockerslimk_3218_20221003093820' id='4977bb26e20eaea81215e54df8a75e95a821d889228210be676ad64853bc181e'
cmd=build info=container status='running' name='dockerslimk_3218_20221003093820' id='4977bb26e20eaea81215e54df8a75e95a821d889228210be676ad64853bc181e'
cmd=build info=container ip='172.17.0.2' message='obtained IP address'
cmd=build info=cmd.startmonitor status='sent'
cmd=build info=event.startmonitor.done status='received'
cmd=build info=container message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER' name='dockerslimk_3218_20221003093820' id='4977bb26e20eaea81215e54df8a75e95a821d889228210be676ad64853bc181e' target.port.list='55018' target.port.info='1300/tcp => 0.0.0.0:55018'
cmd=build state=http.probe.starting message="WAIT FOR HTTP PROBE TO FINISH"
cmd=build info=continue.after mode='probe' message='no input required, execution will resume when HTTP probing is completed'
cmd=build prompt='waiting for the HTTP probe to finish'
cmd=build state=http.probe.running
cmd=build info=http.probe.ports count='1' targets='55018'
cmd=build info=http.probe.commands count='1' commands='GET /'
cmd=build info=http.probe.call status='200' method='GET' target='http://127.0.0.1:55018/' attempt='1' error='none' time='2022-10-03T09:38:32Z'
cmd=build info=http.probe.summary total='1' failures='0' successful='1'
cmd=build state=http.probe.done
cmd=build info=http.probe.crawler url='http://127.0.0.1:55018/' page='0'
cmd=build info=probe.crawler.done addr='http://127.0.0.1:55018/'
cmd=build info=event message='HTTP probe is done'
cmd=build state=container.inspection.finishing
cmd=build state=container.inspection.artifact.processing
cmd=build state=container.inspection.done
cmd=build state=building message="building optimized image"
cmd=build state=completed
cmd=build info=results status='MINIFIED' by='4.99X' size.original='534 MB' size.optimized='107 MB'
cmd=build info=results image.size='107 MB' has.data='true' image.name='dslimexamples/java-dropwizard-standard:slim'
cmd=build info=results artifacts.location='/Users/iximiuz/projects/docker-slim/bin/.docker-slim-state/images/d24ca46f9b60b83f49dcb2182d3d6b6f3b2063c1508cb5a315cd2ef8a68a6160/artifacts'
cmd=build info=results artifacts.report='creport.json'
cmd=build info=results artifacts.dockerfile.reversed='Dockerfile.fat'
cmd=build info=results artifacts.dockerfile.optimized='Dockerfile'
cmd=build info=results artifacts.seccomp='dslimexamples-java-dropwizard-standard-seccomp.json'
cmd=build info=results artifacts.apparmor='dslimexamples-java-dropwizard-standard-apparmor-profile'
cmd=build state=done
cmd=build info=commands message='use the xray command to learn more about the optimize image'
cmd=build info=report file='slim.report.json'
app='docker-slim' message='Join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
app='docker-slim' message='Join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
app='docker-slim' message='GitHub Discussions' info='https://github.com/docker-slim/docker-slim/discussions'
```

Could you share the output of the following:

```
which docker-slim
file $(which docker-slim)

which docker-slim-sensor
file $(which docker-slim-sensor)
```

Also, by any chance, is it ARM64 (i.e., M1/M2 chip)?

**Comment by iximiuz** [comment]
I'm afraid you skipped the results of `file $(which docker-slim)` and `file $(which docker-slim-sensor)`. These would be the most interesting to see. Also, as mitigation, you could try `docker volume ls` and then remove every volume mentioning `docker-slim`.

**Comment by dshamanthreddy** [comment]
@iximiuz gee missed it thanks , but how would I remove the  `local     docker-slim-sensor.1.38.0`, it comes when I do `docker volume ls` PFA

<img width="1512" alt="Screen Shot 2022-10-03 at 8 54 10 AM" src="https://user-images.githubusercontent.com/18470551/193581789-87b01d45-f20e-4b4d-9c5a-231138e63748.png">

**Comment by iximiuz** [comment]
You can try `docker volume rm local docker-slim-sensor.1.38.0`. Overall, your setup looks reasonable to me, so this error you're facing is puzzling. Let me know if `docker volume rm` helped. And also knowing the architecture of the images you're trying to minify might be helpful.

**Comment by dshamanthreddy** [comment]
It still don't help , The issue is on Local mac

**Comment by kcq** [comment]
Also will be good to see what's in the `docker-slim-sensor.1.38.0` volume. There've been a few similar reports in the past for M1, but haven't had much luck reproducing. Possible it's related to file permissions for the sensor.

**Comment by na-ji** [comment]
I had the same issue on M1 MacBook Pro. Deleting the volume didn't solve the issue. However, uninstalling the Homebrew version and installing it manually solved the issue for me.

**Comment by szh** [comment]
I'm having this issue on an Intel Mac.
![image](https://user-images.githubusercontent.com/546965/217096252-2eb1a26b-b021-4fa8-ae8d-b31bb71c8007.png)
