### ISSUE TITLE
Generates 0B File

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [docker-slim/docker-slim#46]
Hey, I ran through the directions and it gave me a 0B file... what am I missing?

**Comment by kcq** [comment]
Thank you for reporting the problem! Can you provide a bit more context? What's your Docker image? What's in it? What is it supposed to do? What ports is it supposed to expose?

**Comment by Jacobh2** [comment]
Having the same problem!

I downloaded the latest Mac binary: `https://github.com/docker-slim/docker-slim/releases/download/1.20/dist_mac.zip`, unzipped it in Downloads and ran:
```
~/D/dist_mac> ./docker-slim build python:3.6.5
docker-slim[build]: state=started
docker-slim[build]: info=params target=python:3.6.5 continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:a5b7afcfdcc878fae7696ea80eecc31114b9c712a1e896cba87a999d255e4a7b size.bytes=911707985 size.human=912 MB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=processing
docker-slim[build]: state=building message='building minified image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY +InfX [911707985 (912 MB) => 0 (0 B)]'
docker-slim[build]: info=results  image.name=python.slim image.size='0 B' data=false
docker-slim[build]: info=results  artifacts.location='/Users/jacobhagstedt/Downloads/dist_mac/.images/a5b7afcfdcc878fae7696ea80eecc31114b9c712a1e896cba87a999d255e4a7b/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=python-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=python-apparmor-profile
docker-slim[build]: state=done
```
The docker-slim outputs that the final image became 0B (the official Python 3.6.5 image) and running `docker images` shows the same result:
```
~/D/dist_mac> docker images
REPOSITORY           TAG              IMAGE ID          CREATED           SIZE
python.slim          latest           7868a2bf7752      3 minutes ago     0B
```

**Comment by psyhomb** [comment]
Anything new on this, I'm having the same problem?

**Comment by Jacobh2** [comment]
Ah, so maybe my test was not a good one for this! Thing is, I got this 0B result on my application Dockerfile also, so I just wanted to do a minimal test.

When you run the `python:3.6.5` image @q-cloudlock which version of the docker-slim are you running? And under which os?

**Comment by kcq** [comment]
@Jacobh2 My version is built from the latest source in master. Also looks like the Docker guys decided to compile their python with "--enable-shared" and it caused that missing shared library problem. There'll be a new release as soon as the shared library problem is resolved. Thanks again for reporting this!

**Comment by kcq** [comment]
The `--debug` and `--show-clogs` flags are useful to get additional debugging information (e.g., `docker-slim --debug build --show-clogs your_app_image_here`). Can you use those flags minifying your image if you still see the 0 byte problem. Hopefully it'll provide some clues...

**Comment by Jacobh2** [comment]
Awesome, thanks! I will try it out again asap and see if it now works!

**Comment by Jacobh2** [comment]
So I finally had some time to test this:

Downloaded the latest [bins for mac](https://github.com/docker-slim/docker-slim/releases/download/1.22/dist_mac.zip) and tested: 
`> ./docker-slim build python:3.6.5` and got:

```
> ./docker-slim build python:3.6.5
docker-slim[build]: state=started
docker-slim[build]: info=params target=python:3.6.5 continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:9a58cce9b09fab822c803138dca676c24c5644ce0a3c6a78418eb05fdb3f3f5a size.bytes=911710465 size.human=912 MB
docker-slim[build]: state=inspecting.container
time="2018-09-24T18:30:41+02:00" level=fatal msg="docker-slim: failure" error="API error (400): {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"exec: \\\"/opt/dockerslim/bin/sensor\\\": permission denied\": unknown"}
" stack="goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc420202360, 0xc42002adc0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x14c59a0, 0xc4201a6f60)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x0, 0x0, 0x147a700, 0x0, 0x0, 0xc4201640c0, 0x7ffeefbffb94, 0xc, 0x0, 0x0, ...)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/commands/build.go:115 +0xc7a
github.com/docker-slim/docker-slim/internal/app/master.init.0.func5(0xc420170140, 0x0, 0xc420170140)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:480 +0xd68
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.HandleAction(0x13db200, 0x14906c8, 0xc420170140, 0xc420168000, 0x0)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:485 +0xc8
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.Command.Run(0x1475209, 0x5, 0x0, 0x0, 0xc42006b370, 0x1, 0x1, 0x1489f8d, 0x3e, 0x0, ...)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/command.go:207 +0xa37
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.(*App).Run(0xc42009ab60, 0xc42001c0c0, 0x3, 0x3, 0x0, 0x0)
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:250 +0x700
github.com/docker-slim/docker-slim/internal/app/master.runCli()
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:730 +0x55
github.com/docker-slim/docker-slim/internal/app/master.Run()
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/app.go:6 +0x25
main.main()
	/Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20
" version="darwin|Tetra|1.22|936f91d2f1f3fc9b09f94e6ce908135108696675|2018-09-08_02:00:42AM (go1.10)"
```

Tried with `sudo ./docker-slim ...` but with the same result!

**Comment by Jacobh2** [comment]
I've finally got around to test this!

`> ./docker-slim build python:3.6.5` now seems to work! 💯 
 
```
> ./docker-slim build python:3.6.5
docker-slim[build]: state=started
docker-slim[build]: info=params target=python:3.6.5 continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:9a58cce9b09fab822c803138dca676c24c5644ce0a3c6a78418eb05fdb3f3f5a size.bytes=911710465 size.human=912 MB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=processing
docker-slim[build]: state=building message='building minified image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY 50.80X [911710465 (912 MB) => 17946656 (18 MB)]'
...
docker-slim[build]: state=done
```

Also tested on the image that I really wanted to work, but there it fails, but I don't that that has to do with this issue!

**Comment by kcq** [comment]
What is the image you really wanted to work? What else is there?

The gotcha with minifying a base python image and not your entire application is that it's not going to include a lot of things because docker-slim doesn't know what your app will need. For example, when I minified the python 3.6.5 image it worked and I did see the python prompt and i was able to run basic python commands, but many features/capabilities were not available because they require dynamic code loading and that code wasn't there.

**Comment by Jacobh2** [comment]
Yeah, I think that is the issue which means I won't be able to use this to get my images smaller unfortunately!

For example, my images fail to run because the module `chardet.sbcsgroupprober` is missing, which is something that is used by the `requests` lib:
```
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from checker import is_time_set
  File "./checker/__init__.py", line 10, in <module>
    from checker.get import get_time
  File "./checker/get.py", line 2, in <module>
    import requests
  File "/usr/local/lib/python3.7/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
  File "/usr/local/lib/python3.7/site-packages/chardet/__init__.py", line 20, in <module>
    from .universaldetector import UniversalDetector
  File "/usr/local/lib/python3.7/site-packages/chardet/universaldetector.py", line 48, in <module>
    from .sbcsgroupprober import SBCSGroupProber
ModuleNotFoundError: No module named 'chardet.sbcsgroupprober'
```

**Comment by Jacobh2** [comment]
Yes, I know. Using the base image was just something I did at the start to see how docker-slim worked :)

The above traceback is from using docker-slim on my image which includes my app! Is there anything specific I can do to make it understand that it shouldn't remove libs that I require? Can I flag them in some way?

**Comment by kcq** [comment]
What kind of application is it? Is it a command line tool or a server? What's the code path where the app gets to use chardet?

One way to make sure the libraries you need are included is to exercise the code path where they are used. For a api/web server it means triggering the appropriate endpoints in your server (using the http probe commands). For cli applications it means passing the appropriate command line arguments for your app when you run `docker-slim build` using the `--cmd` command line argument.

**Comment by kcq** [comment]
There's a low level `--include-path` command line argument to tell DockerSlim that you want the target directory or file to be included in the minified image. It'll be good to add an application level `--ensure-package` to avoid having to locate the package directories/files you need manually.

**Comment by Jacobh2** [comment]
Thanks for the help!

I'll see if I can get the time to test this, right now I'm using the 'slim' python image (`3.6.6-slim-jessie` tag) from the official repo to get a little smaller footprint!

**Comment by kcq** [comment]
With many scripting languages it's important to make sure you execute the key code paths. This is why the `probe` parameter exists when you have a service with an HTTP API. It calls the endpoints you want (defaults to the root path) and it executes the relevant app code paths, which load their dependencies. For the command line applications you can accomplish something similar using you application's command line parameter.
