### ISSUE TITLE
Failed docker-slim build command on WSL(Ubuntu18.04) + Windows10 Pro(ver 1809)

### ISSUE THREAD

**Issue by koki-nakamura22** [docker-slim/docker-slim#61]
Failed docker-slim build command on WSL(Ubuntu18.04) + Windows10 Pro(ver 1809).

My environment is as follows.

# My environment
Host OS: Windows 10 Professional (ver 1809)
Guest OS: Ubuntu18.04(WSL)
Docker ver: 18.06.1-ce, build e68fc7a

I got Ubuntu 18.04 at Microsoft Store.

# Used Dockerfile
```
FROM ubuntu:16.04
CMD echo 'test'
```

# Build Docker Image from Dockerfile
```
cd DockerfileExistDirectory
docker build ./ -t test-ubuntu16.04
```

# Use docker-slim build command to compress the Docker Image.
```
docker-slim build --http-probe test-ubuntu16.04
```

# Message outputted when using docker-slim build command
```
docker-slim[build]: state=started
docker-slim[build]: info=params target=test-ubuntu16.04 continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:9d72150678ef252532c394da38ae24a2d1c0cc76b6cda503da7d4c900c944092 size.bytes=116730674 size.human=117 MB
docker-slim[build]: state=inspecting.container
time="2019-01-03T00:07:13+09:00" level=fatal msg="docker-slim: failure" error="API error (500): {"message":"OCI runtime create failed: container_linux.go:348: starting container process caused \"process_linux.go:402: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/home/k-nakamura/dist_linux/docker-slim-sensor\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/f12b7a174ed167cbd1a2aa4f8c0fa6c475139009f0a3ac5eed8a4ba73b78b8f3/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/f12b7a174ed167cbd1a2aa4f8c0fa6c475139009f0a3ac5eed8a4ba73b78b8f3/merged/opt/dockerslim/bin/sensor\\\\\\\" caused \\\\\\\"device or resource busy\\\\\\\"\\\"\": unknown"}
" stack="goroutine 1 [running]:
runtime/debug.Stack(0x3, 0xc420011b00, 0xc42017c1c0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x8b70c0, 0xc4201c0ac0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x0, 0x0, 0x86c900, 0x0, 0x0, 0xc420089920, 0x7fffe97a666e, 0x10, 0x0, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/commands/build.go:115 +0xc7a
github.com/docker-slim/docker-slim/internal/app/master.init.0.func5(0xc4200d0c80, 0x0, 0xc4200d0c80)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:480 +0xd68
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.HandleAction(0x7cf9a0, 0x882a00, 0xc4200d0c80, 0xc420068400, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:485 +0xc8
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.Command.Run(0x8673b3, 0x5, 0x0, 0x0, 0xc42005d350, 0x1, 0x1, 0x87c272, 0x3e, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/command.go:207 +0xa37
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200a0b60, 0xc42000e0c0, 0x4, 0x4, 0x0, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:250 +0x700
github.com/docker-slim/docker-slim/internal/app/master.runCli()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:730 +0x55
github.com/docker-slim/docker-slim/internal/app/master.Run()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/app.go:6 +0x25
main.main()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20
" version="linux|Tetra|1.22|936f91d2f1f3fc9b09f94e6ce908135108696675|2018-09-08_02:00:42AM (go1.10)"
```

I can't understand to this cause of a problem.

**Comment by kcq** [comment]
Thank you for raising the issue! This is an interesting failure :) This is some kind of volume mounting problem. WSL is not officially supported. Would be great if anybody with Windows can do a bit of research here.

**Comment by koki-nakamura22** [comment]
Thank you for investigate!
I understood.
This issue will closing.
