### ISSUE TITLE
Is there a way to set the http proxy?

### ISSUE THREAD

**Issue by hitenjadeja** [docker-slim/docker-slim#94]
I need to set the http proxy when building. Is there away todo this with docker-slim?
`      
      docker build . \
        -t $IMAGE_NAME \
        --cache-from $CI_REGISTRY/$IMAGE:latest \
        --build-arg HTTP_PROXY=$HTTP_PROXY \
        --build-arg HTTPS_PROXY=$HTTPS_PROXY
      docker-slim build $IMAGE_NAME`

Error: 
`
time="2019-11-19T07:26:48Z" level=error msg="channel.NewCommandClient: NewClient error = wait timeout"
time="2019-11-19T07:26:48Z" level=error msg="ipc.NewClient init error = wait timeout"
time="2019-11-19T07:26:48Z" level=fatal msg="docker-slim: failure" error="wait timeout" stack="goroutine 1 [running]:\nruntime/debug.Stack(0xc0001cff00, 0x1000000000001b8, 0x0)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0xb68a20, 0xc0000916d0)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x9c2e01, 0x0, 0x0, 0x0, 0xc0000aef20, 0xe, 0xa91152, 0x11, 0x1, 0xc0001e0f30, ...)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/commands/build.go:236 +0x12db\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc0001ea160, 0x0, 0xc0001f02b0)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:762 +0x16d8\ngithub.com/urfave/cli.HandleAction(0x9ae380, 0xab4f50, 0xc0001ea160, 0xc0001ea160, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.Command.Run(0xa8776b, 0x5, 0x0, 0x0, 0xc00018a500, 0x1, 0x1, 0xaa9314, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x51c\ngithub.com/urfave/cli.(*App).Run(0xc0001aa000, 0xc000092150, 0x3, 0x3, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x718\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:1139 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim@/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.26.0|660fae2b4fab23a6a80a1d7afe26708e57bac4cb|2019-11-17_01:57:10AM"
`

Any ideas?

**Comment by hitenjadeja** [comment]
ah. im working on a ci pipeline and container is not showing with docker ps.

ill send some more logs shortly

**Comment by hitenjadeja** [comment]
@kcq Actually I dont have anymore logs... :( `docker image ls` is empty. So I assume im stuck...
Might need to build the containers somewhere else and then use docker-slim
